root: /

Home: /

language: zh-CN

#author: iGuan7u
#description: A beautiful & simple theme.

# AvatorURL
# it would be shown on sidecar.

avatar: http://cdn.elselook.com/icon/3000.png?imageView2/1/w/256/h/256

# Comment

gitalk:
  enable: false
  clientID: github_clientID
  clientSecret: github_clientSecret
  repo: you site homepage
  owner: your username
  admin: same as [owner]

disqus:
  enable: false
  shortname: your_disqus_short_name

# Contact_Info
# Contact info will be shown on the side bar.

about: 
  enable: true
  title: 我们的Podcast
  icon: 
  info: 我们每周五晚上，都会上传我们的节目到我们的网站，同时会自动同步到 Apple Podcast，Google Podcast，Spotify，还有各个不同的收听平台。每一期节目我们都会挑选几个近期我们觉得感兴趣的话题和大家分享、用有趣、类似脱口秀的方式讨论我们的观点。以后可能会丰富我们的节目内容，争取形成属于我们自己的风格。<a href='/about/' style='color:#be223a'> 想要了解更多... </a>

contact:
  enable: true
  email: elselook.com@gmail.com
  description: ''

  twitter:
    enable: false
    username: twitter_username

  github:
    enable: false
    username: github_username

  weibo:
    enable: false
    username: weibo_username

  facebook:
    enable: false
    username: facebook_username

  instagram:
    enable: false
    username: instagram_username
    
  youtube:
    enable: false
    username: instagram_username


# Analytice

mta_analytics:
  enable: false
  name: mta_analytics_name
  sid: mta_analytics_sid

baidu_analytics:
  enable: false
  id: baidu_analytice_id

google_analytice:
  enable: false
  tracking_id: google_tracking_id

# Website ICPLicense
# which is useful in China mainland.

ICPLicense:
  enable: true
  content: "苏ICP备15056794号"

# EtraPlugin

extra_plugin:
  enable: false
  url: extra_plugin_js_url

# Development Setting

node_sass:
  # outputStyle: nested
  outputStyle: compressed
  precision: 5
  sourceComments: false
  
## Sitemap
sitemap:
  path: sitemap.xml
  
## Baidusitemap
baidusitemap:
    path: baidusitemap.xml
    
search:
  path: search.xml
  field: post
  content: true
  
